logging:
  level:
    ROOT: WARN
    org.ylzl.eden.gateway: INFO
    org.ylzl.eden.gateway.infrastructure: DEBUG

spring:
  # 缓存数据库
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    timeout: 5000
  # 模板引擎
  thymeleaf:
    cache: true


